### PR TITLE
Fixed None reference when parsing a service which is not a proper URL

### LINKED ISSUE #4: WARNING: Keyring is skipped due to an exception: 'NoneType' object has no attribute 'endswith'
When trying to install a package that's listed in my artifact registry, I get the warning
```
WARNING: Keyring is skipped due to an exception: 'NoneType' object has no attribute 'endswith'
ERROR: Could not find a version that satisfies the requirement <PACKAGE NAME>
ERROR: No matching distribution found for <PACKAGE NAME>
```
and the package is not installed

This seems to be due to my pip.conf mentioning the artifact registry as a `extra-index-url`, rather than `index-url`
If I install the same package with `pip install --index-url https://... <PACKAGE NAME>` it works as expected

### PR DESCRIPTION
**Pull request by ffissore**
Fixes #4

### CODE REVIEW

**Comment by ffissore** [comment]
@googlebot I signed it!

**Comment by ffissore** [comment]
@megan-kuo @Gridasov I've simplified the patch. After looking for why `service` was not a URL, it turned out that pip attempts to find a password using both URL and `netloc` (see [auth.py](https://github.com/pypa/pip/blob/master/src/pip/_internal/network/auth.py#L152)): when given a `netloc`, `urlparse` is unable to parse and returns an object with no hostinfo, hence the `is None` check

**Comment by looztra** [comment]
I got the same problem and was close to provide the exact same PR content.
I confirm that using a package built with this patch saved my day.

**Comment by megan-kuo** [comment]
Thanks for this commit! I've been investigating into this issue as well and realized this was hitting the Keyring exception which causes pip to set Keyring to None.

**Pull request merged**
